# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
# SPDX-License-Identifier: MPL-2.0

name: Rust
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt-get install -y libseccomp-dev
    - name: Build
      run: cargo build --all-features --all-targets
    - name: Run tests
      run: cargo test --all-features --all-targets
    - name: Run cargo clippy
      run: rustup component add clippy && cargo clippy --all-features --all-targets -- -D warnings
    - name: Check formatting
      run: rustup component add rustfmt && cargo fmt --all -- --check
